language: cpp
compiler:
    - gcc
    - clang
branches:
    only:
        - master
notifications:
    recipients:
        - post.travis@gmail.com
    email:
        on_success: change
        on_failure: always
    template:
        - "%{repository}/${branch} (%{commit} - %{author}): %{message}"
os:
    - linux

